ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-1MQKJ3E\deadd];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

